extends:
  - "@epilot/eslint-config"
ignorePatterns:
  - node_modules
  - dist
  - src/__tests__/fixtures/**
  - src/**/*.test.ts
rules:
  "@typescript-eslint/no-unused-vars-experimental": "off"
  "prettier/prettier":
    - error
    - printWidth: 120 # https://hackernoon.com/does-column-width-of-80-make-sense-in-2018-50c161fbdcf6
      trailingComma: all # better diffs, obviously
      bracketSpacing: true # more space = pretty
      semi: true # https://github.com/standard/semistandard
      useTabs: false
      tabWidth: 2
      singleQuote: true
      quoteProps: as-needed
      proseWrap: never
env:
  jest: true
settings:
  cache: true
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
        - ".d.ts"
      paths:
        - src
parserOptions:
  sourceType: module
